services:
  poor-man-dns:
    build: ./poor-man-dns
    cap_add:
      - NET_BIND_SERVICE
    container_name: poor-man-dns
    image: poor-man-dns:latest
    network_mode: host
    restart: always
    volumes:
      - "./poor-man-dns:/poor-man-dns"
